### ISSUE TITLE
Implementing a custom ErrorResponse

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [drewag/Decree#2]
From the API I'm working with, I get error messages in a format like this.

```json
{
  "status": "fail",
  "code": 400,
  "data": null,
  "message": [
    "phoneno: Enter a valid phone no. This value should be 11 digits folowed by + sign."
  ]
}
```

I want to display the strings that come inside the `message` array to the user when an error occurs. So I intended to implement my own `ErrorResponse`.

The problem is it already has a variable called `message`. And it is of type `String`. I can't turn it into a `[String]` because `message` is a required property.

So I put together a workaround like this.

```swift
struct APIErrorResponse: AnyErrorResponse, Decodable {
    let message: String
    let messages: [String]?
    
    enum CodingKeys: String, CodingKey {
        case message = "m"
        case messages = "message"
    }
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        message = ""
        messages = try container.decodeIfPresent([String].self, forKey: .messages)
        print(messages)
    }
}
```

However I'm not getting this response in the `.fail` case where I call the endpoint. I put a breakpoint inside the `nit(from decoder: Decoder)` and the JSON is parsed and the property is assigned the value too but it's not coming to topside. I traced the execution back to the `func parse<Output: Decodable, E: Endpoint>(from data: Data?, for endpoint: E) throws -> Output` method but I'm unable to figure out what goes wrong from there.

**Comment by drewag** [comment]
That is indeed the workaround I would use to parse out a different messages property.

You're seeing an empty error because you are setting the `message` property to an empty string. That makes the final error print out as an empty string.

I recommend changing `message` to a calculated property and removing its coding key. You also don't need to implement the decode initializer as long as you match the coding key name to the property name (which you did). That leaves us with:

```swift
struct APIErrorResponse: AnyErrorResponse, Decodable {
    let messages: [String]?

    var message: String {
        return self.messages?.joined(separator: ", ")
            ?? "Unknown Error"
    }
    
    enum CodingKeys: String, CodingKey {
        case messages = "message"
    }
}
```

I do however recommend making `messages` not optional. Since it is optional, the error response will always decode successfully and you will get just "Unknown Error" instead of something potentially more helpful.

**Comment by Isuru-Nanayakkara** [comment]
Gotcha. Thanks once again :)
